#!/bin/bash
#sudo su - root -c "echo 'phpmyadmin phpmyadmin/reconfigure-webserver multiselect apache2' | debconf-set-selections"
#sudo su - root -c "echo 'phpmyadmin phpmyadmin/dbconfig-install boolean false' | debconf-set-selections"
#sudo apt-get -y install phpmyadmin

sudo apt-get install pwgen -y

MYSQL_ROOT_PASS="1stgroup" # Put yours

PHPMYADMIN_DIR="pmasecret879"      # You don't want script kiddies playing  
                                   # with your default phpMyAdmin install.
AUTOGENERATED_PASS=`PWD123pwd@`

sudo su - root -c "echo 'phpmyadmin phpmyadmin/reconfigure-webserver multiselect apache2' | debconf-set-selections"
sudo su - root -c "echo 'phpmyadmin phpmyadmin/dbconfig-install boolean true' | debconf-set-selections"
sudo su - root -c "echo 'phpmyadmin phpmyadmin/mysql/admin-user string root' | debconf-set-selections"
sudo su - root -c "echo 'phpmyadmin phpmyadmin/mysql/admin-pass password $MYSQL_ROOT_PASS' | debconf-set-selections"
sudo su - root -c "echo 'phpmyadmin phpmyadmin/mysql/app-pass password $AUTOGENERATED_PASS' |debconf-set-selections"
sudo su - root -c "echo 'phpmyadmin phpmyadmin/app-password-confirm password $AUTOGENERATED_PASS' | debconf-set-selections"

apt-get -y install phpmyadmin
sudo ln -s /usr/share/phpmyadmin /var/www/html/phpmyadmin

service apache2 reload
